# Generated by Django 5.2.5 on 2025-08-16 04:59

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.create(
        username='Rhema',
        email='rhemachukwumah7@gmail.com.com',
        password=make_password('rhema7'),
        is_superuser=True,
        is_staff=True,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
    ]
